# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from nltk.stem import WordNetLemmatizer
from secondwindow import Ui_SecondWindow
import csv

class Ui_MainWindow(object):

    def open_window(self):
        # load data
        aI = []
        aF = []
        foodsDict = {}
        f = open("FoodGroups.csv", encoding="utf8")
        r = csv.reader(f)
        for row in r:
            FGL = []
            for index in range(1, len(row)):
                row[index] = row[index] + " "
                FGL.append(row[index])
            foodsDict[row[0]] = FGL
        f.close

        f = open("AllergenIndex.csv", encoding="utf8")
        r = csv.reader(f)
        for row in r:
            row[1] = row[1] + " "
            aI.append(row)
        f.close

        f = open("AllergenFamilies.csv", encoding="utf8")
        r = csv.reader(f)
        for row in r:
            aF.append(row)
        f.close
    
        # identify user allergies
        lst = []
        wnl = WordNetLemmatizer()
        userInfo = [wnl.lemmatize(z.lower()) for z in (a.strip() for a in self.inputBox.toPlainText().splitlines())]

        for x in userInfo:
        # inputBox
            if len(x) > 2:
                if len(lst) > 0 and x == "remove":
                    lst = lst[:-1]
                else:
                    for i in aI:
                        if (x[0].upper() + x[1:] + " ") in i[1]:
                            if not(i in lst):
                                lst.append(i)
                        else:
                            if (x[0].upper() + x[1:].lower()) in foodsDict:
                                for foodGroupItem in foodsDict[x[0].upper() + x[1:]]:
                                    if foodGroupItem in i:
                                        if not(foodGroupItem in lst):
                                            lst.append(i)
        uA = lst

        # generate possible allergies and breakdown
        y = ""
        uRelated = []
        uBreakdown = []
        for i in uA:
            for j in aF:
                if i[0] == j[0]:
                    y = ""
                    for k in j[2:-1]:
                        if not(i[1][:-1] == k):
                            y = y + k.title() + ", "
                            uRelated.append(k.title())
                    if len(uRelated) > 0: 
                        y = y + "and " + j[-1].title()
                    else:
                        y = y + j[-1].title()
                    uRelated.append(j[-1].title())
            uBreakdown.append("Your allergy to " + i[1].upper() + "suggests you could be allergic to " + y)
            y = ""
        if "Lamb'S-Quarters" in uRelated:
            uRelated[uRelated.index("Lamb'S-Quarters")] = "Lamb's Quarters"
        if "Lamb'S-Quarters" in uBreakdown:
            uBreakdown.replace("Lamb'S-Quarters", "Lamb's Quarters")


        # textBox
        totalAllergiesList = []
        for n in uRelated:
            if not(n in [b[1] for b in uA]) and not(n in totalAllergiesList):
                totalAllergiesList.append(n)
        totalAllergies = ""
        for o in totalAllergiesList:
            totalAllergies = totalAllergies + o + "\n"
        bdown = ""
        for p in uBreakdown:
            bdown = bdown + p + "\n\n"

        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SecondWindow()
        self.ui.setupUi(self.window)
        self.ui.allergyBox.setText(totalAllergies)
        self.ui.breakdown = (bdown)
        self.window.showMaximized()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(853, 100, 200, 111))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(64)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(699, 210, 508, 70))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()    
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(786, 260, 334, 70))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.inputBox = QtWidgets.QTextEdit(self.centralwidget)
        self.inputBox.setGeometry(QtCore.QRect(803, 360, 300, 450))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.inputBox.setFont(font)
        self.inputBox.setObjectName("inputBox")
        self.doneButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.open_window())
        self.doneButton.setGeometry(QtCore.QRect(803, 840, 300, 60))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.doneButton.setFont(font)
        self.doneButton.setObjectName("doneButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 842, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Allert"))
        self.label_2.setText(_translate("MainWindow", "Please enter one food allergy per line."))
        self.label_4.setText(_translate("MainWindow", "Click done when finished."))
        self.doneButton.setText(_translate("MainWindow", "Done"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec_())
